import type { MuseBriefContent } from '@/common/types/marketDigest';

/**
 * Sample muse-brief-v1 payload used by the in-app preview (Daily Review →
 * terminal icon). Clearly fake data — lets Kareem review the terminal
 * layout, sections, and animations without waiting for the 8 AM publish job.
 */
export const MUSE_BRIEF_PREVIEW: MuseBriefContent = {
  version: 'muse-brief-v1',
  digest_date: '2026-10-06',
  generated_at: '2026-10-06T08:00:00-04:00',
  silent_update: false,
  market: {
    regime: 'risk-on',
    headline:
      'Futures green into CPI — ES +0.4% with yields steady. Risk-on tape unless 8:30 prints hot; a hot number flips this to chop fast.',
    futures: { es: '+0.4%', nq: '+0.6%' },
    vix: 14.2,
  },
  etfs: [
    {
      ticker: 'SPY',
      score: 82,
      trend: 'up',
      levels: { support: 668, resistance: 682 },
      note: 'Holding above Friday’s high; CPI decides whether 682 gets tested.',
    },
    {
      ticker: 'QQQ',
      score: 78,
      trend: 'up',
      levels: { support: 612, resistance: 628 },
      note: 'Semis leading premarket. NVDA/AVGO green.',
    },
    {
      ticker: 'IWM',
      score: 61,
      trend: 'flat',
      levels: { support: 238, resistance: 246 },
      note: 'Small caps lagging — breadth is the tell today.',
    },
  ],
  sectors: [
    { ticker: 'XLK', name: 'Technology', change_pct: 1.84, change_5d_pct: 3.2 },
    { ticker: 'XLC', name: 'Communication Services', change_pct: 1.21, change_5d_pct: 2.4 },
    { ticker: 'XLI', name: 'Industrials', change_pct: 0.62, change_5d_pct: 1.1 },
    { ticker: 'XLF', name: 'Financials', change_pct: 0.45, change_5d_pct: 0.8 },
    { ticker: 'XLY', name: 'Consumer Discretionary', change_pct: 0.31, change_5d_pct: -0.4 },
    { ticker: 'XLV', name: 'Health Care', change_pct: 0.12, change_5d_pct: 0.5 },
    { ticker: 'XLB', name: 'Materials', change_pct: -0.08, change_5d_pct: -0.9 },
    { ticker: 'XLU', name: 'Utilities', change_pct: -0.34, change_5d_pct: -1.2 },
    { ticker: 'XLP', name: 'Consumer Staples', change_pct: -0.41, change_5d_pct: -0.6 },
    { ticker: 'XLRE', name: 'Real Estate', change_pct: -0.77, change_5d_pct: -1.8 },
    { ticker: 'XLE', name: 'Energy', change_pct: -1.15, change_5d_pct: -2.6 },
  ],
  news: [
    {
      headline: 'CPI due 8:30 AM ET — economists expect +0.3% m/m, +3.0% y/y',
      source: 'Bloomberg',
      url: 'https://www.bloomberg.com',
      tickers: ['SPY', 'QQQ'],
    },
    {
      headline: 'NVDA announces expanded AI datacenter partnership; shares +2.1% premarket',
      source: 'Reuters',
      url: 'https://www.reuters.com',
      tickers: ['NVDA', 'QQQ'],
    },
    {
      headline: 'Fed speakers: Williams (9:00), Cook (12:30) — watch for pushback on cut pricing',
      source: 'WSJ',
      url: 'https://www.wsj.com',
      tickers: ['SPY'],
    },
    {
      headline: 'Oil slips 1.2% as OPEC+ weighs output hike; energy complex soft premarket',
      source: 'CNBC',
      url: 'https://www.cnbc.com',
      tickers: ['XLE'],
    },
  ],
  events: [
    { time_et: '8:30 AM', label: 'CPI (Sep)', consensus: '+0.3% m/m', prior: '+0.4% m/m', impact: 'high' },
    { time_et: '8:30 AM', label: 'Core CPI y/y', consensus: '+3.0%', prior: '+3.1%', impact: 'high' },
    { time_et: '9:00 AM', label: 'Fed Williams speaks', consensus: null, prior: null, impact: 'medium' },
    { time_et: '10:00 AM', label: 'Consumer sentiment (prelim)', consensus: '54.2', prior: '55.1', impact: 'low' },
    { time_et: '12:30 PM', label: 'Fed Cook speaks', consensus: null, prior: null, impact: 'medium' },
  ],
  watch: [
    '8:30 CPI is the whole morning — no new risk before the print, whatever the setup scores say.',
    'If CPI is cool, NQ leads: QQQ 628 is the line. If hot, fade the open spike, don’t chase it.',
    'Breadth check at 10:00 — IWM needs to confirm or the SPY breakout is suspect.',
  ],
  watchlist: [
    {
      ticker: 'AMZN',
      score: 87.8,
      components: { zone: 25, proximity: 12.3, reward_risk: 5.5, trend: 15, rsi: 10, premarket: 10, prior_day: 10 },
      direction: 'PUT',
      setup: 'ORB breakdown',
      if_then: 'If AMZN loses 244.80 on a 1m close with volume > 1.2×, then PUT scalp toward 243.50.',
      invalidation: 'Reclaim of 245.60 kills the breakdown — flat, no second try.',
      levels: { support: 243.5, resistance: 247.5, orh: 246.2, orl: 244.8 },
      premium_tier: 'SCALP_30_100',
    },
    {
      ticker: 'NVDA',
      score: 84.2,
      components: { zone: 23, proximity: 11.2, reward_risk: 6, trend: 15, rsi: 9, premarket: 10, prior_day: 10 },
      direction: 'CALL',
      setup: 'Gap-and-go',
      if_then: 'If NVDA holds above 196.40 through 9:45, then CALL toward 198.50 on the momentum leg.',
      invalidation: 'Flush back under 195.80 means the gap is filling, not going — stand down.',
      levels: { support: 194.2, resistance: 198.5, orh: 197.1, orl: 195.8 },
      premium_tier: 'SCALP_30_100',
    },
    {
      ticker: 'TSLA',
      score: 76.5,
      components: { zone: 20, proximity: 10.5, reward_risk: 6, trend: 12, rsi: 9, premarket: 9, prior_day: 10 },
      direction: 'CALL',
      setup: 'VWAP reclaim',
      if_then: 'If TSLA reclaims VWAP (~441) with a strong 1m close, then CALL toward 444.',
      invalidation: 'Rejection at VWAP twice = no trade. TSLA fakes these.',
      levels: { support: 436.5, resistance: 445, orh: 443.2, orl: 439.8 },
      premium_tier: 'SCALP_50',
    },
    {
      ticker: 'AAPL',
      score: 68.9,
      components: { zone: 18, proximity: 9.4, reward_risk: 5.5, trend: 10, rsi: 8, premarket: 8, prior_day: 10 },
      direction: 'PUT',
      setup: 'Range fade',
      if_then: 'If AAPL tags 264.80 resistance and stalls (wicky 1m candles), then PUT back toward 263.',
      invalidation: 'A 1m close above 265.10 — the range is breaking, not fading.',
      levels: { support: 261.5, resistance: 264.8, orh: 264.2, orl: 262.6 },
      premium_tier: 'SCALP_30_100',
    },
  ],
  muse_picks: [
    {
      ticker: 'AVGO',
      score: 85.1,
      components: { zone: 24, proximity: 11.1, reward_risk: 6, trend: 15, rsi: 9, premarket: 10, prior_day: 10 },
      thesis: 'Unusual premarket volume (+3.2×) with semis leading — riding NVDA’s coattails with a cleaner ORB.',
      direction: 'CALL',
      setup: 'ORB breakout',
      if_then: 'If AVGO breaks 342.50 on volume, then CALL toward 345.',
      invalidation: 'Break fails and AVGO falls back under 341 — false breakout, out.',
      levels: { support: 338, resistance: 345, orh: 342.5, orl: 340.1 },
      premium_tier: 'SCALP_50',
    },
    {
      ticker: 'COIN',
      score: 81.7,
      components: { zone: 22, proximity: 10.7, reward_risk: 6, trend: 14, rsi: 9, premarket: 10, prior_day: 10 },
      thesis: 'BTC +4% overnight — COIN gaps up with crypto beta and tight premarket range.',
      direction: 'CALL',
      setup: 'Gap-and-go',
      if_then: 'If COIN holds 312 through the first 5 minutes, then CALL toward 316.',
      invalidation: 'Under 309.50 the crypto momentum is fading — no chase.',
      levels: { support: 306, resistance: 316, orh: 313.4, orl: 310.2 },
      premium_tier: 'SCALP_30_100',
    },
    {
      ticker: 'AMD',
      score: 74.3,
      components: { zone: 19, proximity: 10.3, reward_risk: 5, trend: 12, rsi: 9, premarket: 9, prior_day: 10 },
      thesis: 'Sympathy move with NVDA/AVGO but weaker structure — secondary play only.',
      direction: 'CALL',
      setup: 'Trend continuation',
      if_then: 'If AMD clears 238.20 with semis still green, then CALL toward 240.',
      invalidation: 'Semis roll over = thesis dead, even if AMD triggers.',
      levels: { support: 234.5, resistance: 240, orh: 238.2, orl: 236.1 },
      premium_tier: 'SCALP_50',
    },
    {
      ticker: 'XLE',
      score: 70.8,
      components: { zone: 18, proximity: 9.8, reward_risk: 5, trend: 11, rsi: 8, premarket: 9, prior_day: 10 },
      thesis: 'Oil soft on OPEC+ headlines — energy weak premarket, short the rip if XLE pops into resistance.',
      direction: 'PUT',
      setup: 'Range fade',
      if_then: 'If XLE pops toward 94.20 and stalls, then PUT back toward 93.40.',
      invalidation: 'Oil headline reversal — XLE over 94.50 kills the fade.',
      levels: { support: 93.4, resistance: 94.2, orh: 93.9, orl: 93.5 },
      premium_tier: 'SCALP_30_100',
    },
  ],
  earnings_blackout: ['JPM', 'WFC'],
  correlation_note:
    'NVDA, AVGO, and AMD are all semi-beta — treat them as ONE position. If you take two, halve size on each.',
};
