import { ORBMonitoringState } from '../useORBMonitoringState';
import type { ORBRange } from '@/common/types/orb';

const TODAY = new Date().toISOString().split('T')[0];

/**
 * Mock data for development/preview purposes - Normal monitoring state
 */
export const MOCK_ORB_DATA: ORBMonitoringState[] = [
  {
    ticker: 'AAPL',
    trade_date: TODAY,
    opening_price: 175.50,
    orb_high: 178.25,
    orb_low: 174.80,
    current_price: 179.10,
    breakout_type: 'Confirmed Bullish',
    breakout_price: 178.30,
    volume: 45230000,
    tracking: null,
    high_broken: true,
    low_broken: false,
    monitoring_active: true,
  },
  {
    ticker: 'TSLA',
    trade_date: TODAY,
    opening_price: 245.30,
    orb_high: 248.90,
    orb_low: 243.15,
    current_price: 242.50,
    breakout_type: 'Bearish',
    breakout_price: 243.00,
    volume: 67890000,
    tracking: null,
    high_broken: false,
    low_broken: true,
    monitoring_active: true,
  },
  {
    ticker: 'MSFT',
    trade_date: TODAY,
    opening_price: 378.20,
    orb_high: 380.45,
    orb_low: 376.80,
    current_price: 379.25,
    breakout_type: 'none',
    breakout_price: null,
    volume: 23450000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
  },
  {
    ticker: 'NVDA',
    trade_date: TODAY,
    opening_price: 485.60,
    orb_high: 492.30,
    orb_low: 483.20,
    current_price: 495.80,
    breakout_type: 'Bullish',
    breakout_price: 492.50,
    volume: 56780000,
    tracking: null,
    high_broken: true,
    low_broken: false,
    monitoring_active: true,
  },
  {
    ticker: 'GOOGL',
    trade_date: TODAY,
    opening_price: 142.40,
    orb_high: 144.20,
    orb_low: 141.50,
    current_price: 140.80,
    breakout_type: 'invalidated',
    breakout_price: null,
    volume: 34560000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
  },
  {
    ticker: 'AMZN',
    trade_date: TODAY,
    opening_price: 152.30,
    orb_high: 154.80,
    orb_low: 151.20,
    current_price: 153.45,
    breakout_type: 'none',
    breakout_price: null,
    volume: 41230000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
  },
  {
    ticker: 'META',
    trade_date: TODAY,
    opening_price: 312.50,
    orb_high: 318.90,
    orb_low: 310.20,
    current_price: 320.15,
    breakout_type: 'Confirmed Bullish',
    breakout_price: 319.00,
    volume: 28940000,
    tracking: null,
    high_broken: true,
    low_broken: false,
    monitoring_active: true,
  },
  {
    ticker: 'AMD',
    trade_date: TODAY,
    opening_price: 128.40,
    orb_high: 131.20,
    orb_low: 127.10,
    current_price: 126.50,
    breakout_type: 'Confirmed Bearish',
    breakout_price: 127.00,
    volume: 52340000,
    tracking: null,
    high_broken: false,
    low_broken: true,
    monitoring_active: true,
  },
  {
    ticker: 'SPY',
    trade_date: TODAY,
    opening_price: 445.20,
    orb_high: 448.50,
    orb_low: 443.80,
    current_price: 446.30,
    breakout_type: 'reversal',
    breakout_price: 448.20,
    volume: 78200000,
    tracking: null,
    high_broken: true,
    low_broken: false,
    monitoring_active: true,
    previous_close: 444.10,
    percentage_change: 0.50,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
    reversal_data: {
      original_breakout_type: 'above',
      reversal_detected_at: new Date().toISOString(),
      confidence: 'HIGH',
      score: 85,
      max_score: 100,
      score_percentage: 85.0,
      vwap: 446.80,
      indicators: [
        'VWAP cross below ($446.80)',
        'Price re-entered ORB (below $448.50)',
        'Decreasing volume on reversal',
        '2 consecutive down bars',
        'Strong bearish reversal candle',
      ],
      reversal_price: 446.30,
      orb_high: 448.50,
      orb_low: 443.80,
      detection_metadata: {
        bars_analyzed: 15,
        reversal_detection_method: 'hybrid',
        indicators_count: 5,
      },
    },
  },
];

/**
 * Mock data for development/preview purposes - Calculation period state
 * This simulates data during the ORB calculation period (9:30-9:45 AM)
 */
export const CALCULATION_MOCK_ORB_DATA: ORBMonitoringState[] = [
  {
    ticker: 'AAPL',
    trade_date: TODAY,
    opening_price: 175.50,
    orb_high: 177.80,
    orb_low: 175.20,
    current_price: 176.45,
    breakout_type: 'none',
    breakout_price: null,
    volume: 12500000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
    previous_close: 175.30,
    percentage_change: 0.66,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
  },
  {
    ticker: 'TSLA',
    trade_date: TODAY,
    opening_price: 245.30,
    orb_high: 247.20,
    orb_low: 244.80,
    current_price: 245.90,
    breakout_type: 'none',
    breakout_price: null,
    volume: 18900000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
    previous_close: 245.10,
    percentage_change: 0.33,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
  },
  {
    ticker: 'MSFT',
    trade_date: TODAY,
    opening_price: 378.20,
    orb_high: 379.50,
    orb_low: 377.90,
    current_price: 378.75,
    breakout_type: 'none',
    breakout_price: null,
    volume: 6800000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
    previous_close: 378.00,
    percentage_change: 0.20,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
  },
  {
    ticker: 'NVDA',
    trade_date: TODAY,
    opening_price: 485.60,
    orb_high: 488.20,
    orb_low: 485.10,
    current_price: 486.80,
    breakout_type: 'none',
    breakout_price: null,
    volume: 15200000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
    previous_close: 485.40,
    percentage_change: 0.29,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
  },
  {
    ticker: 'GOOGL',
    trade_date: TODAY,
    opening_price: 142.40,
    orb_high: 143.10,
    orb_low: 142.20,
    current_price: 142.65,
    breakout_type: 'none',
    breakout_price: null,
    volume: 9800000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
    previous_close: 142.50,
    percentage_change: -0.11,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
  },
  {
    ticker: 'AMZN',
    trade_date: TODAY,
    opening_price: 152.30,
    orb_high: 153.20,
    orb_low: 152.10,
    current_price: 152.75,
    breakout_type: 'none',
    breakout_price: null,
    volume: 11200000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
    previous_close: 152.60,
    percentage_change: 0.10,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
  },
  {
    ticker: 'META',
    trade_date: TODAY,
    opening_price: 312.50,
    orb_high: 314.20,
    orb_low: 312.10,
    current_price: 313.40,
    breakout_type: 'none',
    breakout_price: null,
    volume: 7200000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
    previous_close: 312.80,
    percentage_change: 0.19,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
  },
  {
    ticker: 'AMD',
    trade_date: TODAY,
    opening_price: 128.40,
    orb_high: 129.50,
    orb_low: 128.20,
    current_price: 128.90,
    breakout_type: 'none',
    breakout_price: null,
    volume: 14500000,
    tracking: null,
    high_broken: false,
    low_broken: false,
    monitoring_active: true,
    previous_close: 128.60,
    percentage_change: 0.23,
    data_source: 'alpaca,prev_close:yfinance',
    timestamp: new Date().toISOString(),
  },
];

/**
 * Mock orb_ranges with gap/trend examples for preview.
 * Aligns with MOCK_ORB_DATA tickers so gap badges show when mock mode is on.
 */
export const MOCK_ORB_RANGES: ORBRange[] = [
  {
    ticker: 'AAPL',
    trade_date: TODAY,
    orb_high: 178.25,
    orb_low: 174.80,
    opening_price: 175.50,
    volume_in_range: 45230000,
    prior_close: 176.20,
    today_open: 175.50,
    gap_points: -0.70,
    gap_percent: -0.40,
    gap_direction: 'down',
    prior_day_open: 175.80,
    prior_day_trend: 'bearish',
    trend_continuation: true,
  },
  {
    ticker: 'TSLA',
    trade_date: TODAY,
    orb_high: 248.90,
    orb_low: 243.15,
    opening_price: 245.30,
    volume_in_range: 67890000,
    prior_close: 248.50,
    today_open: 245.30,
    gap_points: -3.20,
    gap_percent: -1.29,
    gap_direction: 'down',
    prior_day_open: 246.00,
    prior_day_trend: 'bearish',
    trend_continuation: true,
  },
  {
    ticker: 'MSFT',
    trade_date: TODAY,
    orb_high: 380.45,
    orb_low: 376.80,
    opening_price: 378.20,
    volume_in_range: 23450000,
    prior_close: 378.15,
    today_open: 378.20,
    gap_points: 0.05,
    gap_percent: 0.01,
    gap_direction: 'flat',
    prior_day_open: 377.90,
    prior_day_trend: 'flat',
    trend_continuation: false,
  },
  {
    ticker: 'NVDA',
    trade_date: TODAY,
    orb_high: 492.30,
    orb_low: 483.20,
    opening_price: 485.60,
    volume_in_range: 56780000,
    prior_close: 482.00,
    today_open: 485.60,
    gap_points: 3.60,
    gap_percent: 0.75,
    gap_direction: 'up',
    prior_day_open: 478.50,
    prior_day_trend: 'bullish',
    trend_continuation: true,
  },
  {
    ticker: 'GOOGL',
    trade_date: TODAY,
    orb_high: 144.20,
    orb_low: 141.50,
    opening_price: 142.40,
    volume_in_range: 34560000,
    prior_close: 144.80,
    today_open: 142.40,
    gap_points: -2.40,
    gap_percent: -1.66,
    gap_direction: 'down',
    prior_day_open: 143.20,
    prior_day_trend: 'bearish',
    trend_continuation: true,
  },
  {
    ticker: 'AMZN',
    trade_date: TODAY,
    orb_high: 154.80,
    orb_low: 151.20,
    opening_price: 152.30,
    volume_in_range: 41230000,
    prior_close: 150.80,
    today_open: 152.30,
    gap_points: 1.50,
    gap_percent: 0.99,
    gap_direction: 'up',
    prior_day_open: 149.50,
    prior_day_trend: 'bullish',
    trend_continuation: true,
  },
  {
    ticker: 'META',
    trade_date: TODAY,
    orb_high: 318.90,
    orb_low: 310.20,
    opening_price: 312.50,
    volume_in_range: 28940000,
    prior_close: 311.00,
    today_open: 312.50,
    gap_points: 1.50,
    gap_percent: 0.48,
    gap_direction: 'up',
    prior_day_open: 310.80,
    prior_day_trend: 'flat',
    trend_continuation: false,
  },
  {
    ticker: 'AMD',
    trade_date: TODAY,
    orb_high: 131.20,
    orb_low: 127.10,
    opening_price: 128.40,
    volume_in_range: 52340000,
    prior_close: 132.00,
    today_open: 128.40,
    gap_points: -3.60,
    gap_percent: -2.73,
    gap_direction: 'down',
    prior_day_open: 133.50,
    prior_day_trend: 'bearish',
    trend_continuation: true,
  },
  {
    ticker: 'SPY',
    trade_date: TODAY,
    orb_high: 448.50,
    orb_low: 443.80,
    opening_price: 445.20,
    volume_in_range: 78200000,
    prior_close: 444.10,
    today_open: 445.20,
    gap_points: -6.10,
    gap_percent: -1.37,
    gap_direction: 'down',
    prior_day_open: 442.00,
    prior_day_trend: 'bearish',
    trend_continuation: true,
  },
];

