-- Daily trade performance reviews generated by Claude.
-- One row per trading day; upsert-safe on review_date.

create table if not exists performance_reviews (
    id           uuid primary key default gen_random_uuid(),
    review_date  date not null unique,
    net_pnl      numeric(10, 2),
    trade_count  integer,
    win_rate     numeric(5, 2),   -- 0–100
    winners      integer,
    losers       integer,
    markdown     text,            -- full Markdown review content
    trades_json  jsonb,           -- snapshot of orb_trades rows for the day
    created_at   timestamptz default now()
);

-- Index for mobile app queries (most-recent-first list)
create index if not exists idx_performance_reviews_date
    on performance_reviews (review_date desc);
